// <auto-generated />
using Karen.Server.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Karen.Server.Migrations
{
    [DbContext(typeof(KarenDbContext))]
    [Migration("20250622110912_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Karen.Common.Storage.Entities.PlayerDetailsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<string>("Figure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("figure");

                    b.Property<int>("Film")
                        .HasColumnType("INTEGER")
                        .HasColumnName("film");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mission");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("PoolFigure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pool_figure");

                    b.Property<bool>("ReceiveNews")
                        .HasColumnType("INTEGER")
                        .HasColumnName("receive_news");

                    b.Property<bool>("Sex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sex");

                    b.Property<int>("Tickets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tickets");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
